"""Keyword scan over harvested metadata (title, abstract, comments).

Zero-download first signal. Hits land in scan_hits with source_kind
'meta:title' / 'meta:abstract' / 'meta:comments'; one scan_items row per
paper proves coverage (immutable-run discipline, see pipeline/scan.py).

Metadata is the LATEST harvested snapshot, so items carry latest_version;
the cohort (created-date window, category rule) is recorded in the run params.

Usage:
    python3 -m pipeline.scan_meta [--from 2026-07-01 --until 2026-08-08]
                                  [--primary-math] [--supersedes meta-v1]
"""

from __future__ import annotations

import argparse
import sys

from . import db, lexicon, runs

SNIPPET_RADIUS = 400


def scan_all(run_id: str, date_from: str | None, date_until: str | None,
             primary_math: bool, supersedes: str | None) -> int:
    con = db.connect()
    q = "SELECT arxiv_id, latest_version, title, abstract, comments FROM papers"
    conds, params = [], []
    if date_from:
        conds.append("created >= ?")
        params.append(date_from)
    if date_until:
        conds.append("created <= ?")
        params.append(date_until)
    if primary_math:
        conds.append("primary_category LIKE 'math%'")
    if conds:
        q += " WHERE " + " AND ".join(conds)
    runs.start_scan_run(con, run_id, "meta", lexicon.LEXICON_VERSION, db.code_commit(),
                        {"from": date_from, "until": date_until,
                         "primary_math": primary_math, "snippet_radius": SNIPPET_RADIUS})
    papers = con.execute(q, params).fetchall()
    n_hits = 0
    hit_rows, item_rows = [], []
    now = runs.utcnow()
    for p in papers:
        n_paper = 0
        for field in ("title", "abstract", "comments"):
            text = p[field]
            if not text:
                continue
            for h in lexicon.find_hits(text):
                lo = max(0, h["offset"] - SNIPPET_RADIUS)
                hi = min(len(text), h["offset"] + SNIPPET_RADIUS)
                hit_rows.append((
                    p["arxiv_id"], p["latest_version"], f"meta:{field}", None,
                    h["term"], h["tier"], h["offset"], text[lo:hi],
                    h["rule_class"], run_id))
                n_paper += 1
        item_rows.append((run_id, p["arxiv_id"], p["latest_version"], None,
                          "ok", n_paper, None, now))
        n_hits += n_paper
    with con:
        con.executemany(
            "INSERT INTO scan_hits (arxiv_id, version, source_kind, file_member, term, tier, "
            "offset, context, rule_class, scan_run) VALUES (?,?,?,?,?,?,?,?,?,?)", hit_rows)
        con.executemany(
            "INSERT INTO scan_items (run_id, arxiv_id, version, artifact_sha256, "
            "status, n_hits, detail, scanned_at) VALUES (?,?,?,?,?,?,?,?)", item_rows)
    runs.finish_scan_run(con, run_id, "complete", len(papers), n_hits, 0,
                         supersedes=supersedes)
    print(f"{len(papers)} papers scanned, {n_hits} hits ({run_id})")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--run", default=None,
                    help="explicit run id (must be unused); default: autogenerated")
    ap.add_argument("--from", dest="date_from", default=None)
    ap.add_argument("--until", dest="date_until", default=None)
    ap.add_argument("--primary-math", action="store_true")
    ap.add_argument("--supersedes", default=None)
    args = ap.parse_args()
    run_id = args.run or runs.new_run_id("meta")
    return scan_all(run_id, args.date_from, args.date_until,
                    args.primary_math, args.supersedes)


if __name__ == "__main__":
    sys.exit(main())
